# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Deploy

on:
  workflow_run:
    workflows:
      -  Test
    types:
      -  completed
jobs:
  deploy:
    if: ${{ github. event.workflow_run.conclusion == 'success' }}
    
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{secrets.AWS_ACCES_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
    - name: CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name pruebafinal \
          --deployment-group-name Deploy \
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}


